### ISSUE TITLE
Unsure where to put scss

### ISSUE THREAD

**Issue by Alysha-94** [funkybob/gilbert#23]
![tree](https://user-images.githubusercontent.com/40345515/60711322-fdc49200-9f57-11e9-993a-22f83b014abb.JPG)

In this structure the scss can be loaded successfully, but we're working around that being displayed in the navbar menu (that displays all pages) by filtering it out.

What is the correct place to put the scss? I've tried putting it in the content folder but then the template page can't find the file.

The template looks for the file like this `<link rel="stylesheet" type="text/css" href="/static/css/base.css">`

@shuttle1987 is happy to contribute docs

**Comment by funkybob** [comment]
In my own site ( https://github.com/funkybob/kitty-litter ) I have it in `pages/css/style.scss` since it's a page I want rendered.

In a more complex site I'm experimenting on porting from hugo, I've the main css file in `pages/css/style.scss`, and in the `config.yml` I have:

```
content_type:
  SCSS:
    output_style: compressed
    include_paths:
      - assets/sass/
```
so the SCSS compiler will import from `assets/sass`  - a new dir next to pages, content, etc.

**Comment by Alysha-94** [comment]
Great, thanks for giving some options
